name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to DO
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to DO
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: root
        key: ${{ secrets.GHA_DEPLOY_KEY }}
        script:
          cd /root/git-training-deploy && bash deploy.sh
